---

- name: Set fact is_container
  ansible.builtin.set_fact:
    is_container: true
  when: >
    (ansible_virtualization_type is defined and
      (ansible_virtualization_type == "docker"
       or ansible_virtualization_type == "containerd"
       or ansible_virtualization_type == "container"
      )
    )

- name: Include dependencies
  ansible.builtin.include_tasks: dependencies.yml
  tags: [install]

- name: Include opencanary
  ansible.builtin.include_tasks: opencanary.yml
  tags: [install, update]
